### PR TITLE
Bump node, npm and deps

### PR DESCRIPTION
**Pull request by blizzz**
* [x] fix: multiselect not showing

the  multiselect  element is there and it has the options applied, but it stays empty and invisible. No options shown when clicking on it.

### CODE REVIEW

**Comment by blizzz** [comment]
required for #340

**Review by juliushaertl — CHANGES_REQUESTED** [review]
I'd suggest to not commit the js bundles in `js/` for non shipped apps unless you want that explicitly to have the app running after git checkout without build steps. So either add them to the gitignore and remove the committed files or at least mark them as binary https://github.com/nextcloud/server/blob/master/.gitattributes#L1-L2

**Comment by juliushaertl** [comment]
Otherwise :+1:

**Comment by blizzz** [comment]
> I'd suggest to not commit the js bundles in `js/` for non shipped apps unless you want that explicitly to have the app running after git checkout without build steps. So either add them to the gitignore and remove the committed files or at least mark them as binary https://github.com/nextcloud/server/blob/master/.gitattributes#L1-L2

Sticked with it for it was already like that before. But yeah, they can actually go.

**Pull request merged**
